import 'dotenv/config';import express from 'express';import cors from 'cors';import OpenAI from 'openai';import fs from 'fs';import path from 'path';import {fileURLToPath} from 'url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));const app=express();app.use(cors());app.use(express.json());const dataDir=path.join(__dirname,'data');fs.mkdirSync(dataDir,{recursive:true});
const store={memories:[],conversations:[],tasks:[],notes:[]};for(const key of Object.keys(store)){const f=path.join(dataDir,key+'.json');if(fs.existsSync(f))try{store[key]=JSON.parse(fs.readFileSync(f,'utf8'))}catch{};}
const save=k=>fs.writeFileSync(path.join(dataDir,k+'.json'),JSON.stringify(store[k],null,2));
app.get('/api/health',(req,res)=>res.json({ok:true,service:'neoverse-backend'}));
app.get('/api/memories',(req,res)=>res.json(store.memories));app.post('/api/memories',(req,res)=>{const m={id:Date.now(),text:String(req.body.text||'').trim(),createdAt:new Date().toISOString()};if(!m.text)return res.status(400).json({error:'text required'});store.memories.push(m);save('memories');res.status(201).json(m)});app.delete('/api/memories/:id',(req,res)=>{store.memories=store.memories.filter(x=>String(x.id)!==req.params.id);save('memories');res.json({ok:true})});
app.get('/api/tasks',(req,res)=>res.json(store.tasks));app.post('/api/tasks',(req,res)=>{const t={id:Date.now(),title:String(req.body.title||'Untitled'),done:false,createdAt:new Date().toISOString()};store.tasks.push(t);save('tasks');res.status(201).json(t)});app.patch('/api/tasks/:id',(req,res)=>{const t=store.tasks.find(x=>String(x.id)===req.params.id);if(!t)return res.status(404).json({error:'not found'});if(typeof req.body.done==='boolean')t.done=req.body.done;save('tasks');res.json(t)});
app.get('/api/notes',(req,res)=>res.json(store.notes));app.post('/api/notes',(req,res)=>{const n={id:Date.now(),title:String(req.body.title||'Note'),content:String(req.body.content||''),createdAt:new Date().toISOString()};store.notes.push(n);save('notes');res.status(201).json(n)});
app.post('/api/ai/chat',async(req,res)=>{const message=String(req.body.message||'').trim();if(!message)return res.status(400).json({error:'message required'});const context=store.memories.slice(-12).map(m=>m.text).join('; ');if(!process.env.OPENAI_API_KEY)return res.json({reply:'NEOVERSE backend is connected. Add OPENAI_API_KEY to enable the real AI model.',mode:'setup'});try{const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const r=await client.chat.completions.create({model:process.env.OPENAI_MODEL||'gpt-4.1-mini',messages:[{role:'system',content:`You are NEOVERSE, a helpful digital assistant. User memory: ${context||'none'}`},{role:'user',content:message}]});res.json({reply:r.choices[0]?.message?.content||'No response.'})}catch(e){console.error(e);res.status(500).json({error:'AI request failed'})}});
app.listen(process.env.PORT||8787,()=>console.log('NEOVERSE backend running on http://localhost:'+(process.env.PORT||8787)));
